# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'media'),
        ),
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
