# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160324_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m/%d'),
        ),
    ]
