# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.text import slugify


def update_slug_field(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for row in Post.objects.all():
        row.slug = slugify(row.title)
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160325_1535'),
    ]

    operations = [
        migrations.RunPython(update_slug_field, reverse_code=migrations.RunPython.noop),
    ]
