# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_update_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
