# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ciaopetroflatpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciaopetroflatpage',
            name='flatpage_ptr',
        ),
        migrations.DeleteModel(
            name='CiaoPetroFlatPage',
        ),
    ]
