# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('blog', '0013_auto_20160330_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery'),
        ),
    ]
