# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160514_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='life', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
    ]
