# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20161106_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
