# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 15:20
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20170409_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=smartfields.fields.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
